apiVersion: v1
name: kvrocks-operator
description: A Helm chart for kvrocks operator
type: application
version: 0.1.1
appVersion: "2.25.0"

dependencies:
  - name: kruise
    version: "1.4.0"
    repository: "https://openkruise.github.io/charts/"
